# Generated by Django 5.0.6 on 2024-05-29 13:16

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_transaction_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("description", tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date"]},
        ),
    ]
