# Generated by Django 5.0.6 on 2024-05-29 13:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_products_alter_transaction_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
