# Generated by Django 5.0.6 on 2024-07-20 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_products_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Products",
        ),
    ]
